
flags: {}

extra-package-dbs: []

packages:
- '.'
- deps/hssqlppp/hssqlppp
- deps/hssqlppp/hssqlppp-th
- deps/snap-loader-static-0.9.0.2

extra-deps:
- resource-pool-catchio-0.2.1.0
- snaplet-postgresql-simple-0.6.0.4
- text-1.2.2.0

resolver: lts-4.2
