
flags: {}

extra-package-dbs: []

packages:
- '.'
- '../budgeteer-lib'
- deps/hssqlppp/hssqlppp
- deps/hssqlppp/hssqlppp-th

extra-deps:
- resource-pool-catchio-0.2.1.0
- snaplet-postgresql-simple-0.6.0.4
- text-1.2.2.0
- snap-loader-static-0.9.0.2
- snap-loader-dynamic-0.9.0.2
- snap-extras-0.11.0.2
- dbmigrations-1.1
- digestive-functors-heist-0.8.6.2
- digestive-functors-snap-0.6.1.3
- readable-0.3.1

resolver: lts-4.2
